#!/usr/bin/env bash

# `readlink -f`
function readlinkf() {
  TARGET=$1
  cd "$(dirname "${TARGET}")"
  TARGET=$(basename "${TARGET}")

  while [ -L "${TARGET}" ]; do
    TARGET=$(readlink "${TARGET}")
    cd $(dirname "${TARGET}")
    TARGET=$(basename "${TARGET}")
  done

  printf "$(pwd -P)/${TARGET}\n"
}

ME=$(readlinkf "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/ag")

for candidate in $(which -a $(basename "$0")); do
  RESOLVED=$(readlinkf "${candidate}")
  if [ "${ME}" != "${RESOLVED}" ]; then
    REAL=${RESOLVED}
  fi
done

if [ -z "${REAL}" ]; then
  printf "%s not found\n" "$(basename "$0")" >&2
  exit 1
fi

exec "${REAL}" --group --color --pager less "$@"
