#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  printf 'usage: %s <term>\n' "$0" >&2
  exit 1
fi

term=$1
shift
# account for preference ladder in `g` and regex syntax differences
if command -v rg &>/dev/null; then
  g "\b${term}\b" "$@"
else
  g "\<${term}\>" "$@"
fi
