#!/usr/bin/env python3

"""
a simple and stupid alternative to sloccount/cloc
"""

import argparse
import collections
import multiprocessing
import sys
from pathlib import Path
from typing import Iterator


def count(path: Path) -> int:
    try:
        # read the file in binary to avoid thinking about unicode
        with open(path, "rb") as f:
            total = 0
            while True:
                c = f.read(1)
                if c == b"":
                    break
                if c == b"\n":
                    total += 1
            return total
    except IOError:
        return 0


def counter(path: Path) -> tuple[str, int]:

    # figure out a category to put it in
    group = path.suffix
    if group == "":
        group = path.name

    return group, count(path)


def get(*paths: str) -> Iterator[Path]:
    """yield all files within a list of paths"""
    for path in paths:
        p = Path(path)
        if p.is_file():
            yield p
        elif p.is_dir():
            for root, _, files in p.walk():
                for f in files:
                    yield root / f
        else:
            raise RuntimeError(f"{p} not found")


def main(args: [str]) -> int:

    # parse command line arguments
    parser = argparse.ArgumentParser(description="simple line counter")
    parser.add_argument("input", nargs="+", help="file or directory to examine")
    options = parser.parse_args(args[1:])

    ret = 0

    if len(options.input) == 1 and Path(options.input[0]).is_file():
        # simply count this file
        print(f"{options.input[0]}: {count(Path(options.input[0]))}")

    else:

        totals = collections.defaultdict(int)
        with multiprocessing.Pool() as pool:
            for group, total in pool.imap_unordered(counter, get(*options.input)):
                totals[group] += total

        # summarise
        for k, v in sorted(totals.items()):
            print(f"{k}: {v}")

    return ret


if __name__ == "__main__":
    sys.exit(main(sys.argv))
