#!/usr/bin/env bash

# unmount all user drives we currently have mounted

ret=0
for i in /media/${USER}/*; do
  if ! mountpoint "$i" &>/dev/null; then
    continue
  fi
  umount "$i"
  if [ $? -eq 0 ]; then
    if which notify-send &>/dev/null; then
      notify-send "$0" "unmounted $i"
    else
      printf "unmounted %s\n" "$i"
    fi
  else
    if which notify-send &>/dev/null; then
      notify-send --urgency=critical "$0" "failed to unmount $i"
    else
      printf "failed to unmount %s\n" "$i" >&2
    fi
    ret=1
  fi
done

exit ${ret}
