#!/usr/bin/env bash

which unclutter &>/dev/null
if [ $? -ne 0 ]; then
  which notify-send &>/dev/null
  if [ $? -eq 0 ]; then
    notify-send --urgency=critical "$0" "unclutter not available"
  else
    echo "unclutter not available" >&2
  fi
  exit 1
fi

ps -C unclutter &>/dev/null
if [ $? -eq 0 ]; then
  which notify-send &>/dev/null
  if [ $? -eq 0 ]; then
    notify-send "$0" "disabling unclutter"
  else
    echo "disabling unclutter"
  fi
  exec killall unclutter
else
  which notify-send &>/dev/null
  if [ $? -eq 0 ]; then
    notify-send "$0" "enabling unclutter"
  else
    echo "enabling unclutter"
  fi
  exec unclutter
fi
