#!/bin/bash

# Restart Thunderbird if it's already running to cope with its shitty
# inability to roam across networks.

which thunderbird &>/dev/null
if [ $? -ne 0 ]; then
  which notify-send &>/dev/null
  if [ $? -eq 0 ]; then
    notify-send --urgency=critical "$0" "thunderbird not available"
  else
    echo "thunderbird not available" >&2
  fi
  exit 1
fi

killall --quiet --wait thunderbird
exec thunderbird
