#!/usr/bin/env bash

if ! which unclutter &>/dev/null; then
  if which notify-send &>/dev/null; then
    notify-send --urgency=critical "$0" "unclutter not available"
  else
    printf "unclutter not available\n" >&2
  fi
  exit 1
fi

if ps -C unclutter &>/dev/null; then
  if which notify-send &>/dev/null; then
    notify-send "$0" "disabling unclutter"
  else
    printf "disabling unclutter\n"
  fi
  exec killall unclutter
else
  if which notify-send &>/dev/null; then
    notify-send "$0" "enabling unclutter"
  else
    printf "enabling unclutter\n"
  fi
  exec unclutter
fi
