#!/usr/bin/env bash

# Restart Thunderbird if it's already running to cope with its shitty
# inability to roam across networks.

if ! which thunderbird &>/dev/null; then
  if which notify-send &>/dev/null; then
    notify-send --urgency=critical "$0" "thunderbird not available"
  else
    printf "thunderbird not available\n" >&2
  fi
  exit 1
fi

killall --quiet --wait thunderbird
exec thunderbird
