#!/bin/zsh

echo "$@" | grep -i '\.BIN$' >/dev/null 2>/dev/null
if [ $? -eq 0 ]; then
    # This is a ripped VCD, hopefully with accompanying CUE
    FNAME=`echo "$@" | sed 's/\.[Bb][Ii][Nn]$//'`
    FNAME=cue://`ls -1 ${FNAME}* | grep -i --color=never '\.CUE$'`:2
else
    FNAME=$@
fi

which mplayer &>/dev/null || {
    echo "mplayer not found" >&2;
    exit 1;
}
mplayer -fs -cache 5000 "${FNAME}"

