#!/bin/bash

# This script finds media in a given folder and plays it in a random order.
# Just like TV :)

# File extensions you want to include.
EXTS='avi mpeg mpg mp4 mkv divx mov rm asf wmv ogv flv'

# Where to look for videos.
MEDIA_ROOT=.

which mplayer >/dev/null 2>/dev/null
if [ $? != 0 ]; then
    echo "Can't find mplayer. Is it installed?" 1>&2
    exit 1
fi

# FIXME: Would be better to generate a find string first then perform the find,
# but I can't get this working and don't have time to troubleshoot it. Below
# works, but not as efficient.
for i in ${EXTS}; do
    find ${MEDIA_ROOT} -iname "*.$i" -and -type f
done | \
 mplayer -fs -playlist - -shuffle
