#!/usr/bin/env bash

# Prefix the output of a command with some given text.

if [ $# -lt 2 ]; then
  printf "Usage: %s text command\n" "$0" >&2
  exit 1
fi

PREFIX=$1
shift

$@ | while read line; do
  printf "%s%s\n" "${PREFIX}" "${line}"
done
exit ${PIPESTATUS[0]}
