#!/usr/bin/python

# Hello, I am Pieman! Defender of the innocent! Propagator of political
# discontent! Occasional dog walker.
#
# Er, anyway, here's man for Python.

import inspect, re, sys

STATEMENTS = frozenset(['assert', 'break', 'continue', 'del', 'exec', 'global',
    'import', 'nonlocal', 'pass', 'print', 'raise', 'return', 'yield'])

def signature(name, argspec):
    args = []
    defaults = argspec[3]
    for i, arg in enumerate(argspec[0]):
        if defaults is not None and len(argspec[0]) - i <= len(defaults):
            args.append('%s=%s' % (arg, defaults[i + len(defaults) - len(argspec[0])]))
        else:
            args.append(arg)
    if argspec[1] is not None:
        args.append('*%s' % argspec[1])
    if argspec[2] is not None:
        args.append('**%s' % argspec[2])
    return '%s(%s)' % (name, ', '.join(args))

def main(argv):
    if len(argv) < 2 or argv[1] == '--help':
        sys.stderr.write('Usage: %s function\n' % argv[0])
        return -1

    call = argv[1]

    if call in STATEMENTS:
        sys.stdout.write('\'%s\' is a statement; refer to online '
            'documentation\n' % call)
        return 0

    # If there's a period in the path, the first component indicates the module
    # in which this function is contained.
    module = None
    if '.' in call:
        m, stem = call.split('.', 1)
        try:
            module = __import__(m)
            call = stem
        except ImportError as e:
            pass

    # Now the function could be either (a) a built-in, (b) a global function,
    # (c) a module itself or (d) a function in a module.
    fn = None
    if module is None:
        try:
            stem = call.split('.')
            fn = getattr(__builtins__, stem[0]) # (a)
            stem = stem[1:]
            while len(stem) > 0:
                fn = getattr(fn, stem[0])
                stem = stem[1:]
        except AttributeError:
            try:
                fn = globals()[call] # (b)
            except KeyError:
                try:
                    fn = __import__(call) # (c)
                except ImportError:
                    fn = None
    else: # (d)
        try:
            bits = call.split('.')
            for b in bits:
                if fn is None:
                    fn = getattr(module, b)
                else:
                    fn = getattr(fn, b)
        except AttributeError:
            pass
    if fn is None:
        sys.stderr.write('Failed to find \'%s\'\n' % argv[1])
        return -1

    try:
        doc = fn.__doc__
        if doc is None:
            raise AttributeError
    except AttributeError:
        sys.stderr.write('No documentation associated with \'%s\'\n' % argv[1])
        return -1

    if inspect.isfunction(fn):
        sys.stdout.write('%s\n\n' %
            signature(fn.__name__, inspect.getargspec(fn)))
    elif inspect.isclass(fn):
        argspec = None
        try:
            argspec = inspect.getargspec(fn.__init__)
        except TypeError:
            # We end up here if the function we were inspecting is implemented
            # in C.
            pass

        if argspec is not None:
            sys.stdout.write('%s\n\n' %
                signature('%s.__init__' % fn.__name__, argspec))
    sys.stdout.write('%s\n' % re.sub(r'^    ', '', doc, flags=re.MULTILINE))

    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))
