#!/bin/bash

# Reptyr requires the scoping limits on Ptrace disabled. This script does such
# a thing.

if [ $# -lt 1 ]; then
    echo "Usage: $0 pid" >&2
    exit 1
fi

echo "Disabling Ptrace scoping limits..."
echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope >/dev/null
reptyr $1
echo "Enabling Ptrace scoping limits..."
echo 1 | sudo tee /proc/sys/kernel/yama/ptrace_scope >/dev/null
