#!/usr/bin/env bash

# Searches for everywhere some pesky command could be hiding.

if [ $# -ne 1 ]; then
  printf "Usage: %s command\n" "$0" >&2
  exit 1
fi

for i in \
      "which" \
      "apt-cache search" \
      "gem search" \
      "gem search -r" \
      "cabal list --simple-output" \
      "pip search" \
      "pip3 search" \
      "port search" \
      "/usr/lib/command-not-found --no-failure-msg" \
      ; do
  # Get the first word of the command to check for existence.
  cmd=${i%% *}
  if which ${cmd} &>/dev/null; then
    $i "$1" 2>&1 | \
      while read line; do
        printf "[%s]: %s\n" "$i" "${line}"
      done
  else
    printf "%s not found, skipping.\n" "${cmd}" >&2
  fi
done
