#!/bin/bash

WIDTH=180 # Characters
HEIGHT=45 # Lines

# Priority of terminal emulators:
if [ $(which rxvt) ]; then
    EMULATOR="rxvt -geometry ${WIDTH}x${HEIGHT}"
elif [ $(which pterm) ]; then
    # To lookup fonts: xlsfonts
    EMULATOR="pterm -geometry ${WIDTH}x${HEIGHT} -sb- -fn -misc-fixed-medium-r-normal--15-140-75-75-c-90-iso10646-1"
elif [ $(which lxterminal) ]; then
    EMULATOR="lxterminal --geometry=${WIDTH}x${HEIGHT}"
else
    # Well this is unpleasant...
    EMULATOR="gnome-terminal --geometry=${WIDTH}x${HEIGHT}"
fi

cd ~/

if [ $(which tmux) ]; then
    RUN="-e tmux"
elif [ $(which screen) ]; then
    RUN="-e screen zsh"
else
    # Curses...
    RUN=
fi

${EMULATOR} ${RUN}
