#!/bin/bash

WIDTH=180 # Characters
HEIGHT=45 # Lines

# Priority of terminal emulators:
which pterm &>/dev/null
if [ $? -eq 0 ]; then
    # To lookup fonts: xlsfonts
    EMULATOR="pterm -geometry ${WIDTH}x${HEIGHT} -sb- -fn -misc-fixed-medium-r-normal--15-140-75-75-c-90-iso10646-1"
else
    which lxterminal &>/dev/null
    if [ $? -eq 0 ]; then
        EMULATOR="lxterminal --geometry=${WIDTH}x${HEIGHT}"
    else
        # Well this is unpleasant...
        EMULATOR="gnome-terminal"
    fi
fi

cd ~/

which tmux &>/dev/null
if [ $? -eq 0 ]; then
    RUN="-e tmux"
else
    which screen &>/dev/null
    if [ $? -eq 0 ]; then
        RUN="-e screen zsh"
    else
        # Curses...
        RUN=
    fi
fi

${EMULATOR} ${RUN}
