#!/usr/bin/env python

'''Unmount all the user drives we currently have mounted.'''

import os, pynotify, subprocess, sys

USER_MOUNT_ROOT = '/media/%s' % os.environ['USER']

pynotify_inited = False
def notify(title, message, urgency=pynotify.URGENCY_NORMAL):
    global pynotify_inited
    if not pynotify_inited:
        pynotify.init('umount_all')
        pynotify_inited = True

    n = pynotify.Notification(title, message)
    n.set_urgency(urgency)
    n.show()
    

umounted = []
for d in os.listdir(USER_MOUNT_ROOT):
    m = os.path.join(USER_MOUNT_ROOT, d)
    if not os.path.ismount(m):
        continue
    try:
        subprocess.check_call(['umount', m])
        umounted.append(m)
    except subprocess.CalledProcessError:
        notify('umount_all', 'failed to unmount %s' % m,
            pynotify.URGENCY_CRITICAL)
if len(umounted) > 0:
    notify('unount_all', 'unmounted %s' % ', '.join(umounted))
